// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------


using System;
using System.Text;
using Mono.Data.Sqlite;
using UnityEngine;
using System.Linq;
using System.Data;

using System.Collections.Generic;

public class MySqlLite
{

	private SqliteConnection m_sqlite;

	public MySqlLite (string a_databaseName)
	{
        if(m_sqlite != null)
        {
            m_sqlite.Close();
        }
		string v_path = Application.streamingAssetsPath;
		m_sqlite = new SqliteConnection ("URI=file:" + v_path + "/" + a_databaseName);

		try
		{
			m_sqlite.Open();  //Initiate connection to the db
		}catch(Exception eg)
        {
			Debug.LogError("Can't open " + a_databaseName);
        }
    }

    public void OnApplicationQuit()
    {
        m_sqlite.Close();
    }

    private void FillDatatable (SqliteCommand a_command, DataTable a_datatable)
	{
		try{
			var v_reader = a_command.ExecuteReader ();


			var v_len = v_reader.FieldCount;

			// Create the DataTable columns
			for (int i = 0; i < v_len; i++) {
				a_datatable.Columns.Add (v_reader.GetName (i), v_reader.GetFieldType (i));
			}

			a_datatable.BeginLoadData ();

			var v_values = new object[v_len];

			// Add data rows
			while (v_reader.Read ()) {
				for (int i = 0; i < v_len; i++)
					v_values [i] = v_reader [i];

				a_datatable.Rows.Add (v_values);
			}

			a_datatable.EndLoadData ();

			v_reader.Close ();
			v_reader.Dispose ();
		}
		catch(Exception _dbnot)
		{
            Debug.Log(m_sqlite);
			Debug.LogError(" DB not Cr8 "+_dbnot);
		}

	}

	public void insertQuery(string a_query)
    {
        try
        {
			SqliteCommand v_cmd;

			v_cmd = m_sqlite.CreateCommand();
			// set the passed query
			v_cmd.CommandText = a_query;
			v_cmd.ExecuteReader();
            Debug.Log("Sucess");
        }
		catch (SqliteException ex)
		{
			//Add your exception code here.
			string msg = ex.Message;

			//int error = 1;
			Debug.Log(msg);
		}
	}

	public DataTable selectQuery (string a_query)
	{
		DataTable v_dataTable = new DataTable ();

//		Debug.Log ("query " + a_query);
	
		try {
			SqliteCommand v_cmd;
			
			v_cmd = m_sqlite.CreateCommand ();
			// set the passed query
			v_cmd.CommandText = a_query;
			//ad = new SqliteDataAdapter(cmd);
			FillDatatable (v_cmd, v_dataTable);
			//ad.Fill(dt); //fill the datasource
		} catch (SqliteException ex) {
			//Add your exception code here.
			string msg = ex.Message;
          
            //int error = 1;
            Debug.LogError(msg);
		}
		

		return v_dataTable;
	}

}


